steps:
    - name: node:12
      entrypoint: npm
      args: ["install"]
    - name: node:12
      entrypoint: npm
      args: ["build"]
    - name: gcr.io/$PROJECT_ID/firebase
      args: ['deploy', "--project", "$PROJECT_ID", '--only=hosting']